### ISSUE TITLE
WebSocket4Net.WebSocket does not contain a definition for NoDelay

### ISSUE THREAD

**Issue by Dids** [schulz3000/deepstreamNet#11]
```
DeepStreamNet/Internals/Connection.cs(20,20): Error CS1061: Type `WebSocket4Net.WebSocket' does not contain a definition for `NoDelay' and no extension method `NoDelay' of type `WebSocket4Net.WebSocket' could be found. Are you missing an assembly reference? (CS1061)
```

**Comment by schulz3000** [comment]
What is the TargetFramework of your project?
The NoDelay property is in WebSocket4Net since ~4 years https://github.com/kerryjiang/WebSocket4Net/blame/109488b21cf10b193775a3f31ce3e757d243df39/WebSocket4Net/WebSocket.cs#L120
The only thing I can see in WebSocket4Net code is that there is a IOS Pragma. Do you have IOS as a target for your project?

**Comment by Dids** [comment]
Ah, yes. I have a Xamarin.Forms project, so I'm targeting both iOS and Android.
I commented out the offending line, and it does still seem to work, but I guess it should be wrapped in a pragma in deepstreamNet itself?

**Comment by Dids** [comment]
@schulz3000 Excellent, thank you! Also, if I may ask, please update the Nuget package when you have a chance. :)
