### ISSUE TITLE
How to handle byte arrays with publish/subcribe?

### ISSUE THREAD

**Issue by Dids** [schulz3000/deepstreamNet#12]
I'm currently trying to see if I can integrate MessagePack (http://msgpack.org) into my app, and while I don't know if deepstream even supports binary data or just strings, I'm successfully packing and unpacking the data.

I can publish the byte data fine, but when I receive it, it comes out as a string in the following format:
```
2XV7IlZlcnNpb24iOjEsIlRpbWVzdGFtcCI6MTQ4OTUwMDA2NywiVGltZXN0YW1wU3RyaW5nIjoibm93IiwiVHlwZSI6MiwiVHlwZVN0cmluZyI6IkxlYXZlIiwiVVVJRCI6IlBhdWxpIiwiVGV4dCI6bnVsbH0=
```

The issue is that I don't know how to deserialize this back into a byte array, which I'm hoping you'd be able to help with? :)

**Comment by schulz3000** [comment]
deepstream do not support binary data right now but you can vote for it here: https://github.com/deepstreamIO/deepstream.io/issues/388
in our dotnet client binary data will be serialized by the sender in a base64 string representation. 
So you can get back your byte array at the receiver with `Convert.FromBase64String(byteArray)`
I can not guarantee that also other deepstream client implementations will support this.
Also you get a small CPU overhead because first you serialize the data with msgpack and then dotnet client need to serialize the byte array again with integrated JSON serializer.

**Comment by Dids** [comment]
Ah I see, got it. Thank you very much. :)
